version: '3'

services:
  Flask_dictionary:
    build: 
      context: .
    ports:
      -"5000"

  nginx:
    image: nginx.latest
    volume:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depents_on:
      - Flask_dictionary
    ports:
      - "80:80"
       